import {useEffect,useRef,useState} from 'react';
import {availableGames,clock,secondsLeft,DASH_LEVELS} from './arcade-core.js';
import {mount2D} from './games-2d.js';
import './arcade.css';
const KEYS={ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right',ArrowUp:'up',w:'up',ArrowDown:'down',s:'down',' ':'action',Enter:'action'};
function Game({game,level,onBack,onScore,breakEnded}){
 const canvas=useRef(null),engine=useRef(null),input=useRef({});
 const [result,setResult]=useState(null),[status,setStatus]=useState('Ready'),[error,setError]=useState(''),[paused,setPaused]=useState(true),[started,setStarted]=useState(false),[ready,setReady]=useState(false),[muted,setMuted]=useState(true),[run,setRun]=useState(0);
 useEffect(()=>{
  let cancelled=false;setResult(null);setError('');setPaused(true);setStarted(false);setReady(false);setStatus(game.three?'Preparing 3D graphics…':'Ready');input.current={};
  async function start(){try{const mount=game.three?(await (import.meta.env.VITE_LOCAL_APP === 'true' ? import('./games-3d.js') : Promise.reject(new Error('3D games are available in BeeBright Local.')))).mount3D:mount2D;if(cancelled)return;engine.current=mount(canvas.current,{id:game.id,level,input:input.current,muted:true,onStatus:s=>{if(!cancelled)setStatus(s);},onFinish:r=>{if(cancelled)return;setResult(r);onScore(game.id,r.score);}});engine.current.pause(true);setReady(true);}catch(e){if(!cancelled)setError(game.three?'3D graphics are unavailable on this device. Choose any of the six 2D games instead.':e.message);}}
  start();const key=(e,value)=>{const action=KEYS[e.key]||KEYS[e.key.toLowerCase()];if(action){e.preventDefault();input.current[action]=value;}if(value&&e.key==='Escape'){setPaused(true);engine.current?.pause(true);}};
  const down=e=>key(e,true),up=e=>key(e,false),hide=()=>{for(const k of Object.keys(input.current))input.current[k]=false;setPaused(true);engine.current?.pause(true);};
  window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',hide);const visibility=()=>{if(document.hidden)hide();};document.addEventListener('visibilitychange',visibility);
  return()=>{cancelled=true;engine.current?.dispose();engine.current=null;window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',hide);document.removeEventListener('visibilitychange',visibility);};
 },[game.id,level,run]);
 useEffect(()=>{if(breakEnded){setPaused(true);engine.current?.pause(true);}},[breakEnded]);
 function pause(){setStarted(true);const value=!paused;setPaused(value);engine.current?.pause(value);}
 function sound(){setMuted(!muted);engine.current?.setMuted(!muted);}
 const control=(action,label)=> <button key={action} aria-label={label} onPointerDown={e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);input.current[action]=true;}} onPointerUp={()=>{input.current[action]=false;}} onPointerCancel={()=>{input.current[action]=false;}} onLostPointerCapture={()=>{input.current[action]=false;}}>{label}</button>;
 return <div className="arcade-player"><div className="arcade-player-bar"><button onClick={onBack}>← All games</button><strong>{game.title}</strong><span role="status">{status}</span><button onClick={pause} disabled={breakEnded||!ready}>{paused?'Resume':'Pause'}</button>{game.id==='dash'&&<button onClick={sound}>{muted?'Sound off':'Sound on'}</button>}</div><div className="arcade-canvas-wrap"><canvas ref={canvas} aria-label={game.title+' playfield'} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);input.current.action=true;}} onPointerUp={()=>{input.current.action=false;}} onPointerCancel={()=>{input.current.action=false;}} onLostPointerCapture={()=>{input.current.action=false;}}/>{(result||error||paused)&&<div className="game-overlay" role="status"><h2>{error?'Graphics unavailable':result?(result.won?'Nicely done!':'One more try?'):started?'Paused':game.title}</h2><p>{error||result?.text||(started?'Your game is paused. Break time keeps counting.':game.controls)}</p>{result&&<p>Score: {result.score}</p>}{!error&&!breakEnded&&<button className="primary" disabled={!ready} onClick={()=>{if(result){setMuted(true);setRun(v=>v+1);}else pause();}}>{result?'Play again':started?'Resume game':ready?'Start game':'Loading…'}</button>}<button className="outline" onClick={onBack}>Choose a game</button></div>}</div><p className="game-instructions">{game.controls} · Escape: pause</p><div className="game-touch-controls">{control('left','←')}{control('up','↑')}{control('down','↓')}{control('right','→')}{control('action',game.id==='bowling'?'Roll':game.id==='gravity'?'Flip':game.id==='space'?'Fire':'Jump / flap')}</div></div>;
}
export default function Arcade({localMode,breakState,onTakeBreak,onFinishBreak,scores,onScore,preview=false}){
 const [game,setGame]=useState(null),[level,setLevel]=useState(0),[now,setNow]=useState(Date.now());const games=availableGames(localMode);
 useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),500);return()=>clearInterval(id);},[]);
 const remaining=breakState?.deadline?secondsLeft(breakState.deadline,now):null,expired=remaining===0;
 return <section className="arcade-page page-width"><div className="arcade-heading"><div><p className="eyebrow">TIME TO UNWIND</p><h1>{preview?'Break arcade':expired?'Break complete':breakState?.deadline?'Your break, your way':'A well-earned pause'}</h1><p>{preview?'Try an original game. No spelling, no scores sent to a server.':breakState?.deadline?'Play a quick game, stretch, or step away from the screen.':`You finished ${breakState?.completed} words. Take a ${breakState?.minutes}-minute break or keep going.`}</p></div>{remaining!==null&&<div className="break-clock" aria-label="Break time remaining">{clock(remaining)}<small>{expired?'Ready when you are':'TIME LEFT'}</small></div>}</div>{!preview&&!breakState?.deadline&&<div className="break-offer"><button className="primary" onClick={onTakeBreak}>Take {breakState?.minutes}-minute break</button><button className="outline" onClick={onFinishBreak}>{breakState?.after==='results'?'See results':'Keep practicing'}</button><p>Short breaks are optional. Finish the whole set to unlock a 25-minute break.</p></div>}{!preview&&breakState?.deadline&&<div className="break-toolbar"><button className="outline" onClick={onFinishBreak}>{breakState.after==='results'?'Return to results':'Return to practice'}</button><p>{expired?'Your break has ended. Your spelling progress is waiting.':'Leaving early ends this break. Switching games keeps the same timer.'}</p></div>}{(preview||breakState?.deadline)&&!expired&&(game?<Game key={game.id+level} game={game} level={level} breakEnded={expired} onBack={()=>setGame(null)} onScore={onScore}/>:<><div className="arcade-cards">{games.map(g=><article className="game-card" key={g.id} style={{'--game-color':g.color}}><div className={'game-poster poster-'+g.id}><span>{({sky:'✈',sheep:'☁',gravity:'↕',bowling:'●',rally:'◈',dash:'◆',marble:'◎',space:'✦'})[g.id]}</span><small>{g.tag}</small></div><div className="game-card-copy"><h2>{g.title}</h2><p>{g.description}</p>{g.id==='dash'&&<label>Course<select aria-label="Neon Dash course" value={level} onChange={e=>setLevel(Number(e.target.value))}>{DASH_LEVELS.map((l,i)=><option value={i} key={l.name}>{i+1}. {l.name}</option>)}</select></label>}{g.id==='marble'&&<label>Course<select aria-label="Marble Run course" value={level<3?level:0} onChange={e=>setLevel(Number(e.target.value))}>{['Harbor','Switchback','Skyline'].map((l,i)=><option value={i} key={l}>{i+1}. {l}</option>)}</select></label>}<div className="game-card-footer"><small>Best {scores?.[g.id]||0}</small><button onClick={()=>{if(g.id==='marble'&&level>2)setLevel(0);setGame(g);}}>Play →</button></div></div></article>)}</div><p className="arcade-note">Original art and music · Scores stay on this device · {localMode?'3D powered by Three.js; requires WebGL 2.':'Five games, all played in your browser.'}</p></>)}</section>;
}
