import {useEffect,useRef,useState} from 'react';
import {desktopRequest,desktopSpeak} from './local-api.js';
import {FEATURES,normalizeStudio,freshStudio,shuffle,dailyWords,summary,achievements,missedWords,LANGUAGES,originMatches,PAIRS,pairWords,choicesFor} from './studio-core.js';
import {saveProgress, deleteSavedProgress} from './api.js';
import {sentenceHint} from './hints.js';

const request=(path,method='GET',value)=>desktopRequest('/api/studio'+path,{method,...(value===undefined?{}:{body:JSON.stringify(value)})});
export function useStudio(userId,localMode) {
  const [data,setData]=useState(freshStudio),[ready,setReady]=useState(false),[error,setError]=useState('');
  const ref=useRef(data), queue=useRef(Promise.resolve());const key='beebright-studio-v2:'+userId;
  useEffect(()=>{let cancelled=false;setReady(false);const load=localMode?request(''):Promise.resolve().then(()=>JSON.parse(localStorage.getItem(key)||'null'));load.then(v=>{if(!cancelled){ref.current=normalizeStudio(v);setData(ref.current);setReady(true);}}).catch(e=>{if(!cancelled){setError(e.message);setReady(true);}});return()=>{cancelled=true;};},[key,localMode]);
  function change(update){const next=normalizeStudio(typeof update==='function'?update(ref.current):update);ref.current=next;setData(next);if(localMode){queue.current=queue.current.catch(()=>{}).then(()=>request('','PUT',next)).catch(e=>setError('Could not save practice tools: '+e.message));}else try{localStorage.setItem(key,JSON.stringify(next));}catch(e){setError('Could not save practice tools: '+e.message);} }
  function record(word,correct,level,listId,kind){change(s=>({...s,events:[...s.events,{id:crypto.randomUUID(),word,correct,level,listId,kind,at:Date.now()}]}));}
  function favorite(word){change(s=>({...s,favorites:s.favorites.includes(word)?s.favorites.filter(w=>w!==word):[...s.favorites,word]}));}
  return {userId,data,ready,error,change,record,favorite,flush:()=>queue.current};
}
function download(value,name){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function PracticeTools({feature,setFeature,studio,localMode,getToken,onStart,onClose}) {
 const [catalog,setCatalog]=useState(null),[notice,setNotice]=useState(''),[list,setList]=useState('study-2027'),[level,setLevel]=useState('one_bee'),[count,setCount]=useState(20),[mode,setMode]=useState('type'),[language,setLanguage]=useState('Greek'),[players,setPlayers]=useState(null),[name,setName]=useState(''),[checks,setChecks]=useState([]),[voices,setVoices]=useState([]),[time,setTime]=useState('18:30'),[duelNames,setDuelNames]=useState(['Player 1','Player 2']),[printSheet,setPrintSheet]=useState(null),[notes,setNotes]=useState('');
 const data=studio.data, stats=summary(data.events);
 useEffect(()=>{let stopped=false;const load=localMode?request('/catalog'):fetch('/study-catalog.json').then(r=>{if(!r.ok)throw new Error('Study catalog unavailable.');return r.json();});load.then(v=>!stopped&&setCatalog(v)).catch(e=>!stopped&&setNotice(e.message));return()=>{stopped=true;};},[localMode]);
 useEffect(()=>{setNotice('');if(localMode&&feature==='profile')request('/profiles').then(setPlayers).catch(e=>setNotice(e.message));if(localMode&&feature==='audio')request('/voices').then(setVoices).catch(e=>setNotice(e.message));if(localMode&&feature==='doctor')request('/doctor').then(setChecks).catch(e=>setNotice(e.message));if(feature==='changelog')fetch(localMode?'/CHANGELOG.md':'/local-changelog.md').then(r=>r.ok?r.text():Promise.reject(new Error('Release notes unavailable.'))).then(setNotes).catch(e=>setNotice(e.message));if(localMode&&feature==='remind')request('/remind').then(v=>v.time&&v.time!=='off'&&setTime(v.time)).catch(e=>setNotice(e.message));},[feature,localMode]);
 useEffect(()=>{if(localMode||!window.speechSynthesis)return;const load=()=>setVoices(window.speechSynthesis.getVoices());load();window.speechSynthesis.addEventListener('voiceschanged',load);return()=>window.speechSynthesis.removeEventListener('voiceschanged',load);},[localMode]);
 const all=catalog?catalog.lists.flatMap(r=>Object.entries(r.levels).flatMap(([l,words])=>words.map(word=>({word,level:l,listId:r.id,source:r.title,hint:{...catalog.hints[word],word}})))):[];
 const chosen=all.filter(w=>w.listId===list&&w.level===level);
 const study=all.filter(w=>w.listId==='study-2027');
 const byWord=new Map([...all,...pairWords()].map(w=>[w.word,w]));
 const meta=FEATURES.find(f=>f[0]===feature);
 function start(kind=feature){if(!studio.ready||!catalog)return;let selected=chosen;let sessionMode=mode;
  if(kind==='daily'){selected=dailyWords(study);sessionMode='type';}
  else if(kind==='review')selected=missedWords(data.events).map(w=>byWord.get(w)).filter(Boolean);
  else if(kind==='favorites')selected=data.favorites.map(w=>byWord.get(w)).filter(Boolean);
  else if(kind==='origins')selected=chosen.filter(w=>originMatches(w.hint,language));
  else if(kind==='pairs')selected=pairWords();
  else if(kind==='compete'||kind==='sprint'||kind==='duel')sessionMode='type';
  if(!selected.length){setNotice('No words available for this selection yet.');return;}
  selected=kind==='daily'?selected:shuffle(selected);
  if(kind==='sprint')selected=selected.slice(0,100);
  else selected=selected.slice(0,kind==='daily'?10:Math.max(1,Math.min(100,Number(count)||20)));
  onStart({words:selected.map(w=>({...w, options:choicesFor(w.word,catalog.distractors?.[w.word]||[])})),mode:sessionMode,kind,level:kind==='pairs'?'pairs':level,listId:list,deadline:kind==='sprint'?Date.now()+120000:null,players:duelNames.map((n,i)=>n.trim()||'Player '+(i+1)),title:meta?.[1]||'Practice'});
 }
 async function backup(){await studio.flush();const v=localMode?await request('/backup'):{app:'BeeBright browser backup',format:1,studio:data,session:JSON.parse(localStorage.getItem('beebright-session-v2:'+studio.userId)||'null')};download(v,'beebright-backup-'+new Date().toISOString().slice(0,10)+'.json');setNotice('Backup downloaded. Keep it somewhere safe.');}
 async function restore(file){if(!file)return;if(file.size>67108864)throw new Error('Choose a backup smaller than 64 MB.');const v=JSON.parse(await file.text());if(!window.confirm('Replace saved practice with this backup?'))return;await studio.flush();if(localMode){await request('/restore','PUT',v);window.location.reload();}else{if(v.app!=='BeeBright browser backup'||v.format!==1||!v.studio)throw new Error('Choose a BeeBright browser backup.');if(v.session && (!Array.isArray(v.session.words)||!v.session.words.length||v.session.words.length>100||!v.session.words.every(w=>typeof w?.word==='string'&&w.word.length<=80)||!Number.isInteger(v.session.index)||v.session.index<0||v.session.index>=v.session.words.length))throw new Error('Invalid saved practice session.');const token=await getToken();if(!token)throw new Error('Sign in again to restore your saved practice session.');if(v.session)await saveProgress(token,v.session);else await deleteSavedProgress(token);studio.change(v.studio);if(v.session)localStorage.setItem('beebright-session-v2:'+studio.userId,JSON.stringify(v.session));else localStorage.removeItem('beebright-session-v2:'+studio.userId);window.location.reload();}}
 function audio(){if(localMode)desktopSpeak('sky').catch(e=>setNotice(e.message));else{const u=new SpeechSynthesisUtterance('The sky was clear today.');u.rate=data.audio.rate;u.volume=data.audio.volume;u.voice=voices.find(v=>v.voiceURI===data.audio.voice)||null;window.speechSynthesis.cancel();window.speechSynthesis.speak(u);}}
 async function player(action,n){await studio.flush();await request('/profiles','PUT',{action,name:n});window.location.reload();}
 const practiceFeatures=['daily','review','compete','sprint','practice','origins','pairs','favorites','duel'];
 return <section className="studio-page page-width"><button className="text-button" onClick={onClose}>← Back to practice</button><p className="eyebrow">YOUR PRACTICE TOOLS</p><h1>{meta?.[1]||'Explore your studio'}</h1><p className="lead">{meta?.[2]||'Choose a tool to build your spelling skills.'}</p><p className="studio-privacy">{localMode?'Saved separately for the active player on this computer.':'Tools and statistics are saved in this browser for your account. Your current practice session also uses the existing cloud save.'}</p>
 {!feature&&<div className="tools-grid">{FEATURES.map(([key,title,description])=><button key={key} onClick={()=>setFeature(key)}><strong>{title}</strong><small>{description}</small>{localMode&&<code>beebright {key}</code>}</button>)}</div>}
 {(notice||studio.error)&&<p role="status" className="settings-notice">{notice||studio.error}</p>}
 {feature&&<button className="text-button" onClick={()=>setFeature('')}>All tools</button>}
 {practiceFeatures.includes(feature)&&<div className="studio-card">
 {!['daily','pairs','review','favorites'].includes(feature)&&<div className="studio-controls"><label>Word list<select value={list} onChange={e=>{setList(e.target.value);setLevel(Object.keys(catalog.lists.find(r=>r.id===e.target.value).levels)[0]);}}>{catalog?.lists.map(r=><option key={r.id} value={r.id}>{r.title}</option>)}</select></label><label>Level<select value={level} onChange={e=>setLevel(e.target.value)}>{Object.keys(catalog?.lists.find(r=>r.id===list)?.levels||{}).map(l=><option key={l} value={l}>{l.replaceAll('_',' ')}</option>)}</select></label></div>}
 {!['daily','sprint'].includes(feature)&&<label>Number of words<input type="number" min="1" max="100" value={count} onChange={e=>setCount(e.target.value)}/></label>}
 {!['daily','compete','sprint','duel'].includes(feature)&&<label>Practice mode<select value={mode} onChange={e=>setMode(e.target.value)}><option value="type">Type the word</option><option value="choice">Multiple choice</option><option value="blank">Fill in the blank</option><option value="flash">Flash cards</option></select></label>}
 {feature==='daily'&&<p>Challenge date: {new Date().toISOString().slice(0,10)} (UTC). The 10 words stay the same throughout the day.</p>}
 {feature==='review'&&<p>{stats.missed.length} words need another attempt. Correctly answering a word removes it from review.</p>}
 {feature==='origins'&&<><label>Language<select value={language} onChange={e=>setLanguage(e.target.value)}>{LANGUAGES.map(l=><option key={l}>{l}</option>)}</select></label><p>Matches language names in the supplied word histories. A word can match more than one language.</p></>}
 {feature==='pairs'&&<div className="pair-lessons">{PAIRS.map(p=><div key={p[0]}><b>{p[0]}</b>: {p[1]}<br/><b>{p[3]}</b>: {p[4]}</div>)}</div>}
 {feature==='favorites'&&<><p>Use “Save word” during practice to add favorites.</p><div className="favorite-list">{data.favorites.map(w=><button key={w} onClick={()=>studio.favorite(w)}>{w} ×</button>)}</div></>}
 {feature==='duel'&&<div className="studio-controls">{duelNames.map((n,i)=><label key={i}>Player {i+1}<input maxLength="40" value={n} onChange={e=>setDuelNames(duelNames.map((p,j)=>j===i?e.target.value:p))}/></label>)}</div>}
 <button className="primary" disabled={!catalog||!studio.ready} onClick={()=>start()}>Start {meta?.[1]?.toLowerCase()}</button></div>}
 {['stats','achievements','lists'].includes(feature)&&<div className="studio-card">{feature==='stats'&&<><div className="result-grid"><div><b>{stats.accuracy}%</b><span>accuracy</span></div><div><b>{stats.mastered}</b><span>distinct words correct</span></div><div><b>{stats.best}</b><span>best answer streak</span></div></div><p>{stats.answers} answers recorded · {stats.missed.length} words to review</p><table><thead><tr><th>Level</th><th>Answers</th><th>Accuracy</th></tr></thead><tbody>{['one_bee','two_bee','three_bee','pairs'].map(l=>{const s=summary(data.events.filter(e=>e.level===l));return <tr key={l}><td>{l.replaceAll('_',' ')}</td><td>{s.answers}</td><td>{s.accuracy}%</td></tr>;})}</tbody></table><p>Words to revisit: {stats.missed.slice(0,30).join(', ')||'None yet.'}</p></>}
 {feature==='achievements'&&<div className="tools-grid">{achievements(data.events).map(a=><article className={a.earned?'earned':'locked'} key={a.name}><strong>{a.earned?'★':'☆'} {a.name}</strong><p>{a.earned?'Earned':'Keep practicing'}</p></article>)}</div>}
 {feature==='lists'&&catalog?.lists.map(r=><div key={r.id}><h2>{r.title}</h2>{Object.entries(r.levels).map(([l,ws])=>{const done=new Set(data.events.filter(e=>e.correct&&e.listId===r.id).map(e=>e.word));return <p key={l}>{l.replaceAll('_',' ')} · {ws.length} words · {Math.round(100*ws.filter(w=>done.has(w)).length/ws.length)}% practiced correctly</p>;})}</div>)}</div>}
 {feature==='profile'&&<div className="studio-card">{localMode?<><p>Switch players after saving and exiting practice. Appearance, favorites, stats and sessions stay separate.</p>{players?.players.map(p=><button className="outline" key={p.id} disabled={players.active===p.id} onClick={()=>player('switch',p.id).catch(e=>setNotice(e.message))}>{p.name}{players.active===p.id?' · active':''}</button>)}<label>New player name<input value={name} maxLength="40" onChange={e=>setName(e.target.value)}/></label><button className="primary" onClick={()=>player('add',name).catch(e=>setNotice(e.message))}>Add player</button></>:<p>Use BeeBright Local for players sharing a laptop without accounts. Website progress is already separated by your signed-in account.</p>}</div>}
 {feature==='backup'&&<div className="studio-card"><p>{localMode?'Back up all local players, settings, statistics and saved sessions.':'Back up browser tools, statistics and the same-device session. This does not back up your Clerk account or all cloud data.'}</p><button className="primary" onClick={()=>backup().catch(e=>setNotice(e.message))}>Download backup</button></div>}
 {feature==='restore'&&<div className="studio-card"><p>Choose a backup from the {localMode?'local':'website'} edition. Existing saved practice will be replaced after confirmation.</p><input type="file" accept=".json,application/json" onChange={e=>restore(e.target.files[0]).catch(e=>setNotice(e.message))}/></div>}
 {feature==='audio'&&<div className="studio-card"><label>Speech speed: {data.audio.rate}<input type="range" min=".3" max="1.5" step=".05" value={data.audio.rate} onChange={e=>studio.change(s=>({...s,audio:{...s.audio,rate:Number(e.target.value)}}))}/></label>{<><label>Volume<input type="range" min="0" max="1" step=".1" value={data.audio.volume} onChange={e=>studio.change(s=>({...s,audio:{...s.audio,volume:Number(e.target.value)}}))}/></label><label>Voice and accent<select value={data.audio.voice} onChange={e=>studio.change(s=>({...s,audio:{...s.audio,voice:e.target.value}}))}><option value="">Default system voice</option>{voices.map(v=><option key={v.voiceURI} value={v.voiceURI}>{v.name} · {v.lang}</option>)}</select></label></>}<button className="primary" onClick={audio}>Test pronunciation</button><p>Voices depend on your operating system. Install offline voices to practice without internet. macOS local speech uses the system volume.</p></div>}
 {feature==='doctor'&&<div className="studio-card">{localMode?checks.map(c=><p key={c.name}><b>{c.ok?'✓':'!'} {c.name}</b>: {c.detail}</p>):<><p>Browser storage: {typeof localStorage!=='undefined'?'available':'unavailable'}</p><p>Speech synthesis: {'speechSynthesis' in window?'available':'unavailable'}</p><p>Study catalog: {catalog?'loaded':'loading'}</p><p>Use <code>beebright doctor</code> to check a local installation.</p></>}</div>}
 {feature==='remind'&&<div className="studio-card">{localMode?<><label>Daily time on this computer<input type="time" value={time} onChange={e=>setTime(e.target.value)}/></label><p>The computer must be awake and you must be signed in. Reopen BeeBright after a restart to resume reminders.</p><button className="primary" onClick={()=>request('/remind','PUT',{time}).then(()=>setNotice('Reminder saved.')).catch(e=>setNotice(e.message))}>Set reminder</button><button className="outline" onClick={()=>request('/remind','PUT',{time:'off'}).then(()=>setNotice('Reminder turned off.')).catch(e=>setNotice(e.message))}>Turn off</button></>:<p>Use <code>beebright remind 18:30</code> in the local edition for an operating-system notification.</p>}</div>}
 {feature==='worksheet'&&<div className="studio-card"><label>Word list<select value={list} onChange={e=>setList(e.target.value)}>{catalog?.lists.map(r=><option key={r.id} value={r.id}>{r.title}</option>)}</select></label><label>Level<select value={level} onChange={e=>setLevel(e.target.value)}>{['one_bee','two_bee','three_bee'].map(l=><option key={l} value={l}>{l.replaceAll('_',' ')}</option>)}</select></label><label>Questions<input type="number" min="1" max="100" value={count} onChange={e=>setCount(e.target.value)}/></label><button className="primary" disabled={!catalog} onClick={()=>setPrintSheet(shuffle(chosen.filter(w=>sentenceHint(w.hint?.sentence,w.word).includes('___'))).slice(0,Math.max(1,Math.min(100,Number(count)||20))))}>Build worksheet</button>{printSheet&&<><button className="outline" onClick={()=>window.print()}>Print / Save as PDF</button><div className="print-worksheet"><h2>BeeBright spelling worksheet</h2><p>Name: ____________________ Date: ______________</p><p>Original practice sentences from BeeBright. Dictionary references and attribution are included in the app.</p><ol>{printSheet.map(w=><li key={w.word}>{sentenceHint(w.hint.sentence,w.word)}</li>)}</ol><div className="worksheet-answers"><h2>Answer key</h2><ol>{printSheet.map(w=><li key={w.word}>{w.word}</li>)}</ol></div></div></>}</div>}
 {feature==='changelog'&&<pre className="studio-card release-notes">{notes||'Loading release notes…'}</pre>}
 </section>;
}
